# This is a generated file. Not intended for manual editing.
services:
  alarm-api:
    build:
      context: "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis"
      dockerfile: "Dockerfile"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57454"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "dialysis.alarm.api:dev"
    ports:
    - "127.0.0.1:57054:57000"
    - "127.0.0.1:57254:57200"
    - "127.0.0.1:57454:57454"
    volumes:
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis/Services/Dialysis.Alarm/Dialysis.Alarm.Api:/app:rw"
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis:/src:rw"
    - "/Users/muhammadahmedshehzad/.nuget/packages:/root/.nuget/packages"
    - "/Users/muhammadahmedshehzad/.local/share/JetBrains/RiderRemoteDebugger/2025.3.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/muhammadahmedshehzad/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2026_2_20_10_32_18:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  cds-api:
    build:
      context: "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis"
      dockerfile: "Dockerfile"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57455"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "dialysis.cds.api:dev"
    ports:
    - "127.0.0.1:57055:57000"
    - "127.0.0.1:57255:57200"
    - "127.0.0.1:57455:57455"
    volumes:
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis/Services/Dialysis.Cds/Dialysis.Cds.Api:/app:rw"
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis:/src:rw"
    - "/Users/muhammadahmedshehzad/.nuget/packages:/root/.nuget/packages"
    - "/Users/muhammadahmedshehzad/.local/share/JetBrains/RiderRemoteDebugger/2025.3.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/muhammadahmedshehzad/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2026_2_20_10_32_18:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  device-api:
    build:
      context: "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis"
      dockerfile: "Dockerfile"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57456"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "dialysis.device.api:dev"
    ports:
    - "127.0.0.1:57056:57000"
    - "127.0.0.1:57256:57200"
    - "127.0.0.1:57456:57456"
    volumes:
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis/Services/Dialysis.Device/Dialysis.Device.Api:/app:rw"
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis:/src:rw"
    - "/Users/muhammadahmedshehzad/.nuget/packages:/root/.nuget/packages"
    - "/Users/muhammadahmedshehzad/.local/share/JetBrains/RiderRemoteDebugger/2025.3.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/muhammadahmedshehzad/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2026_2_20_10_32_18:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  fhir-api:
    build:
      context: "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis"
      dockerfile: "Dockerfile"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57457"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "dialysis.fhir.api:dev"
    ports:
    - "127.0.0.1:57057:57000"
    - "127.0.0.1:57257:57200"
    - "127.0.0.1:57457:57457"
    volumes:
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis/Services/Dialysis.Fhir/Dialysis.Fhir.Api:/app:rw"
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis:/src:rw"
    - "/Users/muhammadahmedshehzad/.nuget/packages:/root/.nuget/packages"
    - "/Users/muhammadahmedshehzad/.local/share/JetBrains/RiderRemoteDebugger/2025.3.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/muhammadahmedshehzad/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2026_2_20_10_32_18:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  gateway:
    build:
      context: "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis"
      dockerfile: "Dockerfile"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57458"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "dialysis.gateway:dev"
    ports:
    - "127.0.0.1:57058:57000"
    - "127.0.0.1:57258:57200"
    - "127.0.0.1:57458:57458"
    volumes:
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis/Gateway/Dialysis.Gateway:/app:rw"
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis:/src:rw"
    - "/Users/muhammadahmedshehzad/.nuget/packages:/root/.nuget/packages"
    - "/Users/muhammadahmedshehzad/.local/share/JetBrains/RiderRemoteDebugger/2025.3.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/muhammadahmedshehzad/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2026_2_20_10_32_18:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  patient-api:
    build:
      context: "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis"
      dockerfile: "Dockerfile"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57459"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "dialysis.patient.api:dev"
    ports:
    - "127.0.0.1:57059:57000"
    - "127.0.0.1:57259:57200"
    - "127.0.0.1:57459:57459"
    volumes:
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis/Services/Dialysis.Patient/Dialysis.Patient.Api:/app:rw"
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis:/src:rw"
    - "/Users/muhammadahmedshehzad/.nuget/packages:/root/.nuget/packages"
    - "/Users/muhammadahmedshehzad/.local/share/JetBrains/RiderRemoteDebugger/2025.3.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/muhammadahmedshehzad/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2026_2_20_10_32_18:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  prescription-api:
    build:
      context: "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis"
      dockerfile: "Dockerfile"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57460"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "dialysis.prescription.api:dev"
    ports:
    - "127.0.0.1:57060:57000"
    - "127.0.0.1:57260:57200"
    - "127.0.0.1:57460:57460"
    volumes:
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis/Services/Dialysis.Prescription/Dialysis.Prescription.Api:/app:rw"
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis:/src:rw"
    - "/Users/muhammadahmedshehzad/.nuget/packages:/root/.nuget/packages"
    - "/Users/muhammadahmedshehzad/.local/share/JetBrains/RiderRemoteDebugger/2025.3.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/muhammadahmedshehzad/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2026_2_20_10_32_18:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  reports-api:
    build:
      context: "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis"
      dockerfile: "Dockerfile"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57461"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "dialysis.reports.api:dev"
    ports:
    - "127.0.0.1:57061:57000"
    - "127.0.0.1:57261:57200"
    - "127.0.0.1:57461:57461"
    volumes:
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis/Services/Dialysis.Reports/Dialysis.Reports.Api:/app:rw"
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis:/src:rw"
    - "/Users/muhammadahmedshehzad/.nuget/packages:/root/.nuget/packages"
    - "/Users/muhammadahmedshehzad/.local/share/JetBrains/RiderRemoteDebugger/2025.3.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/muhammadahmedshehzad/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2026_2_20_10_32_18:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  treatment-api:
    build:
      context: "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis"
      dockerfile: "Dockerfile"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57462"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "dialysis.treatment.api:dev"
    ports:
    - "127.0.0.1:57062:57000"
    - "127.0.0.1:57262:57200"
    - "127.0.0.1:57462:57462"
    volumes:
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis/Services/Dialysis.Treatment/Dialysis.Treatment.Api:/app:rw"
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis:/src:rw"
    - "/Users/muhammadahmedshehzad/.nuget/packages:/root/.nuget/packages"
    - "/Users/muhammadahmedshehzad/.local/share/JetBrains/RiderRemoteDebugger/2025.3.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/muhammadahmedshehzad/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2026_2_20_10_32_18:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
