# This is a generated file. Not intended for manual editing.
services:
  alarm-api:
    build:
      context: "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis"
      dockerfile: "Dockerfile"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57427"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "dialysis.alarm.api:dev"
    ports:
    - "127.0.0.1:57027:57000"
    - "127.0.0.1:57227:57200"
    - "127.0.0.1:57427:57427"
    volumes:
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis/Services/Dialysis.Alarm/Dialysis.Alarm.Api:/app:rw"
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis:/src:rw"
    - "/Users/muhammadahmedshehzad/.nuget/packages:/root/.nuget/packages"
    - "/Users/muhammadahmedshehzad/.local/share/JetBrains/RiderRemoteDebugger/2025.3.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/muhammadahmedshehzad/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2026_2_19_23_39_28:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  cds-api:
    build:
      context: "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis"
      dockerfile: "Dockerfile"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57428"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "dialysis.cds.api:dev"
    ports:
    - "127.0.0.1:57028:57000"
    - "127.0.0.1:57228:57200"
    - "127.0.0.1:57428:57428"
    volumes:
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis/Services/Dialysis.Cds/Dialysis.Cds.Api:/app:rw"
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis:/src:rw"
    - "/Users/muhammadahmedshehzad/.nuget/packages:/root/.nuget/packages"
    - "/Users/muhammadahmedshehzad/.local/share/JetBrains/RiderRemoteDebugger/2025.3.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/muhammadahmedshehzad/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2026_2_19_23_39_28:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  device-api:
    build:
      context: "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis"
      dockerfile: "Dockerfile"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57429"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "dialysis.device.api:dev"
    ports:
    - "127.0.0.1:57029:57000"
    - "127.0.0.1:57229:57200"
    - "127.0.0.1:57429:57429"
    volumes:
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis/Services/Dialysis.Device/Dialysis.Device.Api:/app:rw"
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis:/src:rw"
    - "/Users/muhammadahmedshehzad/.nuget/packages:/root/.nuget/packages"
    - "/Users/muhammadahmedshehzad/.local/share/JetBrains/RiderRemoteDebugger/2025.3.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/muhammadahmedshehzad/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2026_2_19_23_39_28:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  fhir-api:
    build:
      context: "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis"
      dockerfile: "Dockerfile"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57430"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "dialysis.fhir.api:dev"
    ports:
    - "127.0.0.1:57030:57000"
    - "127.0.0.1:57230:57200"
    - "127.0.0.1:57430:57430"
    volumes:
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis/Services/Dialysis.Fhir/Dialysis.Fhir.Api:/app:rw"
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis:/src:rw"
    - "/Users/muhammadahmedshehzad/.nuget/packages:/root/.nuget/packages"
    - "/Users/muhammadahmedshehzad/.local/share/JetBrains/RiderRemoteDebugger/2025.3.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/muhammadahmedshehzad/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2026_2_19_23_39_28:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  gateway:
    build:
      context: "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis"
      dockerfile: "Dockerfile"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57431"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "dialysis.gateway:dev"
    ports:
    - "127.0.0.1:57031:57000"
    - "127.0.0.1:57231:57200"
    - "127.0.0.1:57431:57431"
    volumes:
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis/Gateway/Dialysis.Gateway:/app:rw"
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis:/src:rw"
    - "/Users/muhammadahmedshehzad/.nuget/packages:/root/.nuget/packages"
    - "/Users/muhammadahmedshehzad/.local/share/JetBrains/RiderRemoteDebugger/2025.3.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/muhammadahmedshehzad/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2026_2_19_23_39_28:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  patient-api:
    build:
      context: "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis"
      dockerfile: "Dockerfile"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57432"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "dialysis.patient.api:dev"
    ports:
    - "127.0.0.1:57032:57000"
    - "127.0.0.1:57232:57200"
    - "127.0.0.1:57432:57432"
    volumes:
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis/Services/Dialysis.Patient/Dialysis.Patient.Api:/app:rw"
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis:/src:rw"
    - "/Users/muhammadahmedshehzad/.nuget/packages:/root/.nuget/packages"
    - "/Users/muhammadahmedshehzad/.local/share/JetBrains/RiderRemoteDebugger/2025.3.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/muhammadahmedshehzad/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2026_2_19_23_39_28:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  prescription-api:
    build:
      context: "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis"
      dockerfile: "Dockerfile"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57433"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "dialysis.prescription.api:dev"
    ports:
    - "127.0.0.1:57033:57000"
    - "127.0.0.1:57233:57200"
    - "127.0.0.1:57433:57433"
    volumes:
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis/Services/Dialysis.Prescription/Dialysis.Prescription.Api:/app:rw"
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis:/src:rw"
    - "/Users/muhammadahmedshehzad/.nuget/packages:/root/.nuget/packages"
    - "/Users/muhammadahmedshehzad/.local/share/JetBrains/RiderRemoteDebugger/2025.3.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/muhammadahmedshehzad/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2026_2_19_23_39_28:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  reports-api:
    build:
      context: "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis"
      dockerfile: "Dockerfile"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57434"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "dialysis.reports.api:dev"
    ports:
    - "127.0.0.1:57034:57000"
    - "127.0.0.1:57234:57200"
    - "127.0.0.1:57434:57434"
    volumes:
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis/Services/Dialysis.Reports/Dialysis.Reports.Api:/app:rw"
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis:/src:rw"
    - "/Users/muhammadahmedshehzad/.nuget/packages:/root/.nuget/packages"
    - "/Users/muhammadahmedshehzad/.local/share/JetBrains/RiderRemoteDebugger/2025.3.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/muhammadahmedshehzad/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2026_2_19_23_39_28:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  treatment-api:
    build:
      context: "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis"
      dockerfile: "Dockerfile"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57435"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "dialysis.treatment.api:dev"
    ports:
    - "127.0.0.1:57035:57000"
    - "127.0.0.1:57235:57200"
    - "127.0.0.1:57435:57435"
    volumes:
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis/Services/Dialysis.Treatment/Dialysis.Treatment.Api:/app:rw"
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Dialysis:/src:rw"
    - "/Users/muhammadahmedshehzad/.nuget/packages:/root/.nuget/packages"
    - "/Users/muhammadahmedshehzad/.local/share/JetBrains/RiderRemoteDebugger/2025.3.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/muhammadahmedshehzad/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2026_2_19_23_39_28:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
